export const GET_ACCOUNT = "GET_ACCOUNT";
export const SET_ACCOUNT_LOADING = "SET_ACCOUNT_LOADING";

export const GET_FINANCE = "GET_FINANCE";
export const SET_FINANCE_LOADING = "SET_FINANCE_LOADING";

export const SET_TXNCARD_LOADING = "SET_TXNCARD_LOADING";
export const GET_TXNCARD = "GET_TXNCARD";

export const SET_TXNLIST_LOADING = "SET_TXNLIST_LOADING";
export const GET_TXNSLIST = "GET_TXNSLIST";


export const GET_INTERACTIONS = "GET_INTERACTIONS";
export const SET_INTERACTIONS_LOADING = "SET_INTERACTIONS_LOADING";

export const GET_CC_TXNS = "GET_CC_TXNS";
export const SET_CC_TXNS_LOADING = "SET_CC_TXNS_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ERRORS = "SET_ERRORS";
